name: Rake installer  
jobs:
description: 'Install Rake'
runs:
  using: "composite"  
  steps:              
    - name: Install Rake
      run: bundle exec rake install
      shell: bash
    - name: Build rake
      run: bundle exec rake build
      shell: bash
