name: MySQL installer  
description: 'Install a mysql instance for the tests to run'
jobs:

runs:
  using: "composite"  
  steps:
    - name: Environment variables
      env:        
        CI: true
        RAILS_ENV: test
        RACK_ENV: test
        DISABLE_SPRING: 1
      run: echo "Environment variables were set up for MySQL"
      shell: bash    
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
      shell: bash
    - name: Set mysql root password
      run: echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" | sudo mysql -uroot -proot      
      shell: bash
