name: Get Secrets
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:        
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:    
      - name: Get actions code
        run: echo "$SAUCE_USERNAME"
