name: Mysql installer
on: workflow_call
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
    steps:
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Set mysql root password
        run: echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" | sudo mysql -uroot -proot
