name: Run UI tests composite actions
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get actions code
        uses: actions/checkout@v3
      - name: say-hello
        uses: ./.github/actions/hello_world
