name: Run UI tests composite actions
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
      - name: say-hello
        uses: actions/hello_world@022f68a5edf040a0268b6d0ef0bfbefba40a595e
