name: Run UI tests composite actions
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:        
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1    
      CIRCLE_NODE_INDEX: 1
      CIRCLE_NODE_TOTAL: 1
    steps:    
      - name: Get actions code
        uses: actions/checkout@v3    
      - name: say-hello
        uses: ./.github/actions/hello_world        
      - name: Install mysql
        uses: ./.github/actions/install-mysql                    
      - name: Install test variables
        uses: ./.github/actions/test-variables-installer      
      - name: Install test variables
        uses: ./.github/actions/install-ui-test-variables              
      - name: Install Ruby
        uses: ./.github/actions/install-ruby
      - name: Install node
        uses: ./.github/actions/install-node        
      - name: Install rake
        uses: ./.github/actions/install-rake
      - name: Rake run UI tests
        run: bundle exec rake circle:run_ui_tests --trace
      - name: debugging
        run: echo "$CIRCLE_NODE_TOTAL"
