name: Install Ruby and gems
on: workflow_call
jobs:
  build:
    uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
    with:
      ruby-version: 2.5
      bundler-cache: true        
