
name: Run UI Test Parallel
on: workflow_dispatch
jobs:  
  validate-changes-on-repo:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  
    strategy: 
      matrix:
        environment: [ubuntu-latest]
        product: ['dashboard', 'pegasus', 'shared', 'lib', 'bin_i18n']
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"    
      - run: echo "::set-output name=matrix::{\"project\":$$}"
  use-output:
    needs: validate-changes-on-repo
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
