name: Run UI tests 2
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
      
    steps:    
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Set mysql root password
        run: echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" | sudo mysql -uroot -proot


      - name: Setup locals
        run: |
          echo "
          bundler_use_sudo: false
          cloudfront_key_pair_id: $CLOUDFRONT_KEY_PAIR_ID
          cloudfront_private_key: \"$CLOUDFRONT_PRIVATE_KEY\"
          ignore_eyes_mismatches: true
          disable_all_eyes_running: true
          use_my_apps: true
          build_dashboard: true
          build_pegasus: true
          build_apps: true
          localize_apps: true
          dashboard_enable_pegasus: true
          dashboard_workers: 5
          skip_seed_all: true
          optimize_webpack_assets: false
          optimize_rails_assets: false
          google_maps_api_key: boguskey
          dashboard_db_reader: \"mysql://readonly@localhost/dashboard_test\"
          " >> locals.yml

          
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          ruby-version: 2.5
          bundler-cache: true
          
      - name: Install packages
        run: |
          sudo apt-get update
        
      - name: Rake Install
        run: bundle exec rake install

      - name: Rake Build
        run: bundle exec rake build
        
  printing-exit:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good bye"
