name: Run UI tests 2
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
      
    steps:    
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Set mysql root password
        run: echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" | sudo mysql -uroot -proot


      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          ruby-version: 2.5
          bundler-cache: true
          
      - name: Rake Install
        run: bundle exec rake install

      - name: Rake Build
        run: bundle exec rake build
        
  printing-exit:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Good bye"
