
name: Run UI Test Parallel
on: workflow_dispatch
jobs:  
  validate-changes-on-repo:
    outputs:
      matrix: ${{ steps.validate-changes-on-repo.outputs.matrix }}  
    strategy: 
      matrix:
        environment: [ubuntu-latest]
        product: ['dashboard', 'pegasus', 'shared', 'lib', 'bin_i18n']
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=matrix::{\"project\":".$$."}"
  use-output:
    needs: validate-changes-on-repo
    strategy:
      matrix: ${{fromJson(needs.validate-changes-on-repo.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
