name: Test ssh
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
    steps:    
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3  
